### ISSUE TITLE
[Solved in 1.1.2] Support for client 2.2.4?

### ISSUE THREAD

**Issue by scomoletti** [tomaskir/NetXMS-csv-importer#1]
Any plans to add support for 2.2.4? I gave the current version a try against my 2.2.4 server but it failed with the following error:

java -jar netxms-csv-importer-1.1.1.jar 
Application starting.
Loading configuration properties file.
Loading nodes from the .csv file.
Found 362 nodes in .csv file.
Connecting to the NetXMS server.
Exception in thread "main" java.lang.NoClassDefFoundError: org/netxms/base/Logger
	at org.netxms.client.NXCSession.connect(NXCSession.java:1800)
	at org.netxms.client.NXCSession.connect(NXCSession.java:1777)
	at com.github.tomaskir.netxms.csvimporter.netxms.NetxmsConnector.connect(NetxmsConnector.java:28)
	at com.github.tomaskir.netxms.csvimporter.Application.main(Application.java:35)
Caused by: java.lang.ClassNotFoundException: org.netxms.base.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

**Comment by tomaskir** [comment]
Hi,

Sorry for the late reply, I was at a conference last week.

Sadly, this is an issue in the NetXMS API client, so there is not much I can do about it in the importer.

Tagging @alkk for help with this.

**Comment by alkk** [comment]
I've pushed proper client libraries to sonatype, they should be propagated to maven central in under two hours.

**Comment by tomaskir** [comment]
This should now be fixed in Importer release 1.1.2.

Please let me know if it works properly now.

Thanks!
